# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [35]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [36]:
imported_csv = "output_data/cities.csv"
new_weather_df = pd.read_csv(imported_csv)
new_weather_df.head()

,Unnamed: 0,City,Lat,Lon,Temp,Humidity,Cloudiness,Wind Speed (mph)
0,0,Provideniya,64.38,-173.30,57.20,67,10,15.66
1,1,Llanes,43.42,-4.75,65.21,98,0,1.99
2,2,Ak-Dovurak,51.18,90.60,74.05,43,85,1.32
3,3,Rikitea,-23.12,-134.97,66.94,71,20,20.74
4,4,Qaanaaq,77.48,-69.36,45.75,57,0,5.28

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [37]:
gmaps.configure(api_key=g_key)

In [38]:
locations = new_weather_df[["Lat", "Lon"]].astype(float)
humidity = new_weather_df["Humidity"].astype(float)

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [48]:
perfect_weather_df = new_weather_df.loc[(new_weather_df["Temp"]<= 80)]
#[(new_weather_df["Temp"]> 65)][(new_weather_df["Humidity"]< 60)]

hotel_df = perfect_weather_df

hotel_df["Hotel Name"] = ""
hotel_df.head()

C:\Users\force\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0,City,Lat,Lon,Temp,Humidity,Cloudiness,Wind Speed (mph),Hotel Name
0,0,Provideniya,64.38,-173.30,57.20,67,10,15.66,
1,1,Llanes,43.42,-4.75,65.21,98,0,1.99,
2,2,Ak-Dovurak,51.18,90.60,74.05,43,85,1.32,
3,3,Rikitea,-23.12,-134.97,66.94,71,20,20.74,
4,4,Qaanaaq,77.48,-69.36,45.75,57,0,5.28,

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [49]:
#params
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Identify Hotels
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lon = row["Lon"]
    target_city = row["City"]

    # iterate locations
    params["location"] = f"{lat},{lon}"

    # Set Base URL
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)

    # convert to json
    name_address = name_address.json()

    # Fill countries without available hotel with "Not Available".
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]

    except (KeyError, IndexError):
        hotel_df.loc[index, "Hotel Name"] = "Not Available"

hotel_df

C:\Users\force\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Unnamed: 0,City,Lat,Lon,Temp,Humidity,Cloudiness,Wind Speed (mph),Hotel Name
0,0,Provideniya,64.38,-173.30,57.20,67,10,15.66,Not Available
1,1,Llanes,43.42,-4.75,65.21,98,0,1.99,Hotel La Paz
2,2,Ak-Dovurak,51.18,90.60,74.05,43,85,1.32,"Gostinitsa ""Cheleesh"""
3,3,Rikitea,-23.12,-134.97,66.94,71,20,20.74,Pension Maro'i
4,4,Qaanaaq,77.48,-69.36,45.75,57,0,5.28,Qaanaaq Hotel
5,5,Talnakh,69.49,88.40,62.60,67,0,26.84,Talnakh Hotel
6,6,Campo Largo,-25.46,-49.53,39.67,99,31,1.01,Hotel Campo Largo Express
7,7,Mataura,-46.19,168.86,45.05,91,92,5.28,Ellie's Villa
8,8,Saldanha,-33.01,17.94,51.80,93,100,8.05,Blue Bay Lodge
9,9,Barrow,71.29,-156.79,33.80,86,90,10.29,King Eider Inn
10,10,Hermanus,-34.42,19.23,51.01,81,100,8.99,Misty Waves Boutique Hotel
11,11,Khatanga,71.97,102.50,63.30,46,0,19.37,"Gostinitsa ""Zapolyar'ye"""
12,12,Tomatlán,19.93,-105.25,78.10,83,100,1.59,Norma franco
16,16,Bluff,-46.60,168.33,50.50,78,57,18.72,Bluff Homestead - Guesthouse & Campervan Park
17,17,Kapaa,22.08,-159.32,77.72,74,40,19.46,Sheraton Kauai Resort at Coconut Beach
18,18,Cayenne,4.93,-52.33,75.20,100,99,1.12,Hôtel Le Dronmi
19,19,Hilo,19.73,-155.09,72.45,65,90,4.70,Hilo Hawaiian Hotel
21,21,Deputatsky,69.30,139.90,63.23,44,72,3.83,Baza Otdykha
23,23,Waitara,-38.92,174.25,48.99,69,4,5.01,Not Available
24,24,Albany,42.60,-73.97,76.51,93,1,4.63,Not Available
26,26,Dikson,73.51,80.55,45.03,79,0,13.27,Not Available
27,27,Ushuaia,-54.80,-68.30,33.80,69,20,4.70,Albatros Hotel
29,29,Souillac,-20.52,57.52,68.00,88,75,14.99,Bils' Villa
30,30,Rafaela,-31.25,-61.49,46.60,58,0,5.01,Parra Hotel & Suites
31,31,Thompson,55.74,-97.86,60.80,87,90,5.82,Burntwood Hotel
32,32,Deutschlandsberg,46.82,15.22,61.23,87,0,2.24,JUFA Hotel Deutschlandsberg – Sport-Resort
33,33,Nsoko,-27.03,31.95,55.40,87,0,1.12,KaMsholo Bushveld Safaris
35,35,Ancud,-41.87,-73.82,38.66,93,20,6.93,HOTEL ANCUD DON LUCAS
36,36,Jardim,-21.48,-56.14,56.71,67,76,4.09,Hotel Estância
37,37,Vaini,-21.20,-175.20,75.20,88,75,8.05,Keleti Beach Resort
38,38,Touros,-5.20,-35.46,73.40,94,40,2.24,INN NEW HORIZON
39,39,Evensk,61.95,159.23,59.23,80,95,7.49,Not Available
40,40,Bulnes,-36.74,-72.30,52.66,100,90,17.22,"Casa de Adobe, Natural y Más"
41,41,Bredasdorp,-34.53,20.04,50.00,93,100,9.17,Bredasdorp Country Manor
43,43,Pevek,69.70,170.31,44.38,95,92,5.59,Severnoye Zoloto

In [50]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>

</dl>
"""
#<dt>Country</dt><dd>{Country}</dd>
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in perfect_weather_df.iterrows()]
locations = perfect_weather_df[["Lat", "Lon"]]

In [51]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))